### Use the following code for the questions below:

In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### How many negative numbers are there?

In [5]:
a < 0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [6]:
a[a<0]

array([-2, -1, -6, -7])

In [7]:
len(a[a<0])

4

### How many positive numbers are there?

In [8]:
len(a[a>0])

5

### How many even positive numbers are there?

In [10]:
pos_nums = a[a>0]

In [11]:
pos_nums

array([ 4, 10, 12, 23,  3])

In [12]:
pos_nums[pos_nums % 2 == 0]

array([ 4, 10, 12])

In [13]:
len(pos_nums[pos_nums % 2 == 0])

3

### if you were to add 3 to each data point, how many positive numbers would there be?

In [20]:
a+3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [22]:
len(a[(a+3)>0])

10

### If you squared each number, what would the new mean and standard deviation be?

In [23]:
a_squared = a ** 2

In [24]:
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [25]:
a_squared.mean()

74.0

In [26]:
a_squared.std()

144.0243035046516

### A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0.

In [27]:
centered_a = a - a.mean()

In [28]:
centered_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [29]:
centered_a.mean()

0.0

### Calculate the z-score for each data point.

In [30]:
z_scores = centered_a / a.std()

In [31]:
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### Use the more numpy practice link and follow the questions within it.
### Setup 1

In [32]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Use python's built in functionality/operators to determine the following:
### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [33]:
type(a)

list

In [34]:
sum(a)

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [35]:
min(a)

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [36]:
max(a)

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [37]:
sum(a) / len(a)

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [38]:
prod_a = 1
for n in a:
    prod_a *= n

In [39]:
prod_a

3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [40]:
[n ** 2 for n in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [41]:
[n for n in a if n % 2 != 0]

[1, 3, 5, 7, 9]

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [42]:
[n for n in a if n % 2 == 0]

[2, 4, 6, 8, 10]

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [44]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b2 = np.array(b)

In [46]:
b

[[3, 4, 5], [6, 7, 8]]

In [45]:
b2

array([[3, 4, 5],
       [6, 7, 8]])

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [47]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [48]:
sum_of_b

33

In [51]:
b2.sum()

33

### Exercise 2 - refactor the following to use numpy. 

In [52]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [53]:
min_of_b

3

In [55]:
b2.min()

3

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [56]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [57]:
max_of_b

8

In [58]:
b2.max()

8

### # Exercise 4 - refactor the following using numpy to find the mean of b

In [59]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [60]:
mean_of_b

5.5

In [61]:
b2.mean()

5.5

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [62]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [63]:
product_of_b

20160

In [65]:
b2.prod()

20160

In [64]:
np.prod(b2)

20160

### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [66]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [67]:
squares_of_b

[9, 16, 25, 36, 49, 64]

In [70]:
np.square(b2)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [71]:
b2 ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

### Exercise 7 - refactor using numpy to determine the odds_in_b

In [72]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [73]:
odds_in_b

[3, 5, 7]

In [74]:
b2[b2 % 2 != 0]

array([3, 5, 7])

### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [75]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [76]:
evens_in_b

[4, 6, 8]

In [77]:
b2[b2 % 2 == 0]

array([4, 6, 8])

### Exercise 9 - print out the shape of the array b.

In [78]:
b2.shape

(2, 3)

### Exercise 10 - transpose the array b.

In [79]:
b2

array([[3, 4, 5],
       [6, 7, 8]])

In [80]:
b2.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [81]:
b2.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [82]:
b2.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [84]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [ ]:
c = np.array(c)

### Exercise 1 - Find the min, max, sum, and product of c.

In [85]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

### Exercise 2 - Determine the standard deviation of c.

In [86]:
c.std()

2.581988897471611

### Exercise 3 - Determine the variance of c.

In [87]:
c.var()

6.666666666666667

### Exercise 4 - Print out the shape of the array c

In [88]:
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.

In [89]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Exercise 6 - Get the dot product of the array c with c.

In [90]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [91]:
np.sum(c * c.transpose())

261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [92]:
np.prod(c * c.transpose())

131681894400

### Setup 4

In [93]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

### Exercise 1 - Find the sine of all the numbers in d

In [95]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - Find the cosine of all the numbers in d

In [96]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - Find the tangent of all the numbers in d

In [97]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d

In [98]:
d[d < 0]

array([-90, -30, -45, -45])

### Exercise 5 - Find all the positive numbers in d

In [99]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

### Exercise 6 - Return an array of only the unique numbers in d.

In [100]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.

In [101]:
len(np.unique(d))

11

### Exercise 8 - Print out the shape of d.

In [102]:
d.shape

(3, 6)

### Exercise 9 - Transpose and then print out the shape of d.

In [103]:
d.transpose().shape

(6, 3)

### Exercise 10 - Reshape d into an array of 9 x 2

In [105]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])