# Numpy Lecture

## Imports

In [1]:
import numpy as np

## Creating an array

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

## Referencing the values in an array

In [3]:
my_array = np.array([1, 2, 3, 4, 5])

### Just like an list, we can access the values of a basic array with integer indexing

In [4]:
my_list = [1, 2, 3, 4, 5]

In [5]:
my_list[0]

1

In [6]:
my_array[0]

1

## Lists of lists and array of arrays

### We have made a list of lists

In [7]:
list_of_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

### We access the elements in these lists by repeatedly using integer indexing

In [8]:
list_of_list[1][1]

5

### With arrays we can make an array of arrays, also known as a matrix or a multidimensional array

In [14]:
matrix = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Unlike list of lists, we can access the elements inside much quicker

In [16]:
matrix[1, 1]

5

### In a two dimensional array, the first indexing number is the row and the second is the column

```python
matrix[row, column]
```

### We can access multiple elements in an array using slicing, like we did with lists

In [18]:
my_list[1:]

[2, 3, 4, 5]

In [19]:
my_array[1:]

array([2, 3, 4, 5])

### But unlike list of lists, I can do this with the multidimensional array too

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
matrix[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Indexing with a boolean sequence, also known as a boolean mask

In [26]:
my_array

array([1, 2, 3, 4, 5])

In [31]:
mask = [False, True, False, True, False]

my_array[mask]

array([2, 4])

## Vectorized Operations

### Adding 1 to every element of a list

### Fails to just say list + 1

In [32]:
my_list

[1, 2, 3, 4, 5]

In [33]:
my_list + 1

TypeError: can only concatenate list (not "int") to list

### Using a for loop

In [34]:
list_with_one_added = []

for n in my_list:
    list_with_one_added.append(n + 1)
    
list_with_one_added

[2, 3, 4, 5, 6]

### Using list comprehension

In [35]:
my_list

[1, 2, 3, 4, 5]

In [36]:
[n + 1 for n in my_list]

[2, 3, 4, 5, 6]

In [37]:
my_array

array([1, 2, 3, 4, 5])

In [38]:
my_array + 1

array([2, 3, 4, 5, 6])

In [39]:
my_array

array([1, 2, 3, 4, 5])

### It works with our other mathmatical operators too

In [40]:
my_array - 5

array([-4, -3, -2, -1,  0])

In [41]:
my_array * 10

array([10, 20, 30, 40, 50])

In [42]:
my_array / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [43]:
my_array // 2

array([0, 1, 1, 2, 2])

In [44]:
my_array % 2

array([1, 0, 1, 0, 1])

In [45]:
my_array ** 5

array([   1,   32,  243, 1024, 3125])

### We can even vectorize our comparison operators

In [47]:
my_array

array([1, 2, 3, 4, 5])

In [46]:
my_array > 2

array([False, False,  True,  True,  True])

### We can use this boolean array to get back values that return True

In [52]:
my_array[my_array > 2]

array([3, 4, 5])

### In depth dive of what is happening with the comparison

In [56]:
my_array

array([1, 2, 3, 4, 5])

In [51]:
my_array[my_array % 2 == 0]

array([2, 4])

In [63]:
my_array % 2

array([1, 0, 1, 0, 1])

In [64]:
my_array % 2 == 1

array([ True, False,  True, False,  True])

In [65]:
new_array = my_array[my_array % 2 == 1]
new_array

array([1, 3, 5])

In [66]:
new_array[new_array > 2]

array([3, 5])

## Array Creation

### `np.random.randn()`

In [67]:
np.random.randn(10)

array([-0.89729204, -0.40444927, -0.05538905,  0.12858356,  1.48131705,
       -1.0538831 ,  0.19190845,  0.22649762, -0.87491354, -0.46327487])

In [69]:
np.random.randn(2, 2)

array([[ 1.29377326, -0.70328551],
       [-1.56569791, -1.61719496]])

###  `np.zeros()` & `np.ones()` & `np.full()`

In [70]:
np.zeros(3)

array([0., 0., 0.])

In [73]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones(3)

array([1., 1., 1.])

In [75]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.full(3, 15)

array([15, 15, 15])

In [77]:
np.full((3, 3), 15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

### `np.arange()`

In [78]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

#### What about decimals?

In [82]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### `np.linspace()`

In [86]:
np.linspace(1, 4, 5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

## Array Methods

###  `array.mean()`

In [87]:
my_array

array([1, 2, 3, 4, 5])

In [88]:
my_array.mean()

3.0

###  `array.min()`

In [89]:
my_array.min()

1

###  `array.max()`

In [90]:
my_array.max()

5

###  `array.sum()`

In [91]:
my_array.sum()

15

###  `array.std()`

In [92]:
my_array.std()

1.4142135623730951

In [93]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
matrix.mean()

5.0